version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: habbit_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A habbit_tracker worker --loglevel=info
    depends_on:
      - redis
      - db

volumes:
  postgres_data: